### ISSUE TITLE
herokuで動作しているサービス上でsigninができない

### ISSUE THREAD

**Issue by takatori** [takatori-task/lgtm#28]
# 問題の概要

heroku上にデプロイしたサービスでsing inできない

```
[error] - play.api.libs.CryptoConfigParser - The application secret has not been set, and we are in prod mode. Your application is not secure.
2015-12-21T09:04:51.898007+00:00 app[web.1]: [error] - play.api.libs.CryptoConfigParser - To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret
2015-12-21T09:04:51.903045+00:00 app[web.1]: [error] - application -
2015-12-21T09:04:51.903049+00:00 app[web.1]:
2015-12-21T09:04:51.903051+00:00 app[web.1]: ! @6og1i5j56 - Internal server error, for (GET) [/signin] ->
2015-12-21T09:04:51.903051+00:00 app[web.1]:
2015-12-21T09:04:51.903052+00:00 app[web.1]: play.api.UnexpectedException: Unexpected exception[ProvisionException: Unable to provision, see the following errors:
2015-12-21T09:04:51.903053+00:00 app[web.1]:
2015-12-21T09:04:51.903054+00:00 app[web.1]: 1) Error in custom provider, @6og1i5j55: Configuration error
2015-12-21T09:04:51.903054+00:00 app[web.1]:   while locating play.api.libs.CryptoConfigParser
2015-12-21T09:04:51.903055+00:00 app[web.1]:   while locating play.api.libs.CryptoConfig
2015-12-21T09:04:51.903056+00:00 app[web.1]:     for parameter 0 at play.api.libs.Crypto.<init>(Crypto.scala:282)
2015-12-21T09:04:51.903057+00:00 app[web.1]:   at play.api.inject.BuiltinModule.bindings(BuiltinModule.scala:48):
2015-12-21T09:04:51.903058+00:00 app[web.1]: Binding(class play.api.libs.Crypto to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
2015-12-21T09:04:51.903058+00:00 app[web.1]:   while locating play.api.libs.Crypto
2015-12-21T09:04:51.903059+00:00 app[web.1]:
2015-12-21T09:04:51.903060+00:00 app[web.1]: 1 error]
```
# 再現の手順
- [heroku](https://takatori-lgtm.herokuapp.com)にアクセスする
- sing inボタンを押す
# 修正すべき内容
- 不明

**Comment by takatori** [comment]
APPLICATION_SECRETの設定を追加することで解決
